version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Using pre-installed Maven"

  build:
    commands:
      - echo "Building application …"
      - mvn clean package -DskipTests

  post_build:
    commands:
      - echo "Packaging Elastic Beanstalk artifact …"
      - mkdir eb-deploy
      - cp target/*.jar eb-deploy/application.jar
      - cp -R ebextensions eb-deploy/
      - cd eb-deploy
      - zip -r ../application.zip .

artifacts:
  files:
    - application.zip
