version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Using pre-installed Maven"

  pre_build:
    commands:
      - echo "Setting environment variables..."
      - export SERVER_PORT=8080
      - export SPRING_PROFILES_ACTIVE=prod

  build:
    commands:
      - echo "Building application..."
      - mvn clean package -DskipTests
      - echo "Verifying JAR file..."
      - ls -l target/*.jar
      - echo "Verifying ebextensions directory..."
      - ls -la .ebextensions/

  post_build:
    commands:
      - echo "Packaging Elastic Beanstalk artifact..."
      - mkdir -p eb-deploy
      - cp target/*.jar eb-deploy/application.jar
      - cp -R .ebextensions eb-deploy/
      - cd eb-deploy
      - zip -r ../application.zip .

artifacts:
  files:
    - application.zip
  discard-paths: yes
