version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo ">> Using Corretto 21 and pre-installed Maven"
  pre_build:
    commands:
      - echo ">> Setting environment variables"
      - export SERVER_PORT=8080
      - export SPRING_PROFILES_ACTIVE=prod
  build:
    commands:
      - echo ">> Building JAR with Maven"
      - mvn clean package -DskipTests
      - echo ">> Verifying target JAR exists"
      - ls -l target/*.jar
  post_build:
    commands:
      - echo ">> Preparing files for deployment"
      # Rename the JAR to application.jar
      - cp target/*.jar application.jar
      # Verify all required files exist
      - ls -l application.jar Procfile .ebextensions
artifacts:
  files:
    - application.jar
    - Procfile
    - .ebextensions/**/*