version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "Using pre-installed Maven"

  pre_build:
    commands:
      - echo "Setting environment variables..."
      - export SERVER_PORT=8080
      - export SPRING_PROFILES_ACTIVE=prod

  build:
    commands:
      - echo "Building application JAR..."
      - mvn clean package -DskipTests
      - echo "Ensuring target JAR exists:"
      - ls -l target/*.jar

  post_build:
    commands:
      - echo "Staging Elastic Beanstalk artifact structure..."
      - rm -rf eb-deploy && mkdir eb-deploy
      - cp target/*.jar eb-deploy/application.jar
      - cp -R .ebextensions eb-deploy/
      - cp Procfile eb-deploy/Procfile
      - echo "Artifact staging complete."

artifacts:
  files:
    - eb-deploy/**/*
  discard-paths: no
