version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo ">> Using Corretto 21 and pre-installed Maven"
  pre_build:
    commands:
      - echo ">> Setting environment variables"
      - export SERVER_PORT=8080
      - export SPRING_PROFILES_ACTIVE=prod
  build:
    commands:
      - echo ">> Building JAR with Maven"
      - mvn clean package -DskipTests
      - echo ">> Verifying target JAR exists"
      - ls -l target/*.jar
  post_build:
    commands:
      - echo ">> Staging EB artifact structure"
      - rm -rf eb-deploy && mkdir eb-deploy
      - cp target/*.jar eb-deploy/application.jar
      - cp Procfile eb-deploy/Procfile
      - cp -R .ebextensions eb-deploy/.ebextensions
      - cd eb-deploy
      - echo ">> Zipping bundle into application.zip"
      - zip -r ../application.zip .
artifacts:
  files:
    - application.zip
  discard-paths: yes
